# -*- coding: utf-8 -*-
"""multiagentdemo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJS87vyuQesjdicUiuoBW457xnJhTyv4
"""



!pip install -U langgraph langchain-groq langchain-community tavily-python
!pip install arxiv

import os
from typing import Annotated, TypedDict, List, Dict, Any
from typing_extensions import Literal

# GROQ and LangChain Imports
from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_community.utilities import ArxivAPIWrapper
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.graph import StateGraph, START, END
from google.colab import userdata



try:
    os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')
    os.environ["TAVILY_API_KEY"] = userdata.get('TAVILY_API_KEY')
    print("Groq client initialized successfully.")
except Exception as e:
    print(f"Error initializing Groq client. Make sure your API key is set correctly. Error: {e}")
    client = None

# --- 1. STATE DEFINITION ---

class AgentState(TypedDict):
    """The state of the research assistant."""
    messages: Annotated[list[BaseMessage], lambda x, y: x + y]
    domain: str
    basic_problem: str
    research_gaps: List[str]
    paper_draft: Dict[str, str]
    next_step: str

# --- 2. AGENT INITIALIZATION (GROQ) ---

# Using Llama 3 70B for high-quality reasoning, or 8B for extreme speed
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.1,
    max_retries=2
)
search_tool = TavilySearchResults(max_results=3)
arxiv_tool = ArxivAPIWrapper()

def create_agent(llm, tools, system_prompt: str):
    """Helper to bind tools and system prompts to the GROQ model."""
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="messages"),
    ])
    if tools:
        return prompt | llm.bind_tools(tools)
    return prompt | llm

# --- 3. NODE DEFINITIONS ---

def explorer_node(state: AgentState):
    """Searches for relevant papers using Tavily and ArXiv."""
    explorer_prompt = f"""You are the SBU Search Specialist using GROQ speed.
    Domain: {state['domain']}
    Current Problem: {state['basic_problem']}

    Task: Find the 3 most relevant current papers.
    Focus on specific methodologies and architectural trends."""

    agent = create_agent(llm, [search_tool], explorer_prompt)
    response = agent.invoke(state)
    return {"messages": [response], "next_step": "reviewer"}

def reviewer_node(state: AgentState):
    """Identifies research gaps in the gathered data."""
    reviewer_prompt = f"""You are the Literature Reviewer.
    Analyze gathered info and identify 3 'Research Gaps'.
    What is missing in {state['domain']} regarding {state['basic_problem']}?"""

    agent = create_agent(llm, None, reviewer_prompt)
    response = agent.invoke(state)

    gaps = [line for line in response.content.split('\n') if 'gap' in line.lower()][:3]

    return {
        "messages": [response],
        "research_gaps": gaps,
        "next_step": "writer"
    }

def writer_node(state: AgentState):
    """Drafts formal paper sections based on the gaps."""
    writer_prompt = f"""You are the Academic Paper Architect.
    Gaps: {state['research_gaps']}
    Draft: Abstract, Intro, Methodology, Proposed Arch, and Conclusion.
    Tone: Formal Academic."""

    agent = create_agent(llm, None, writer_prompt)
    response = agent.invoke(state)

    return {
        "messages": [response],
        "paper_draft": {"full_report": response.content},
        "next_step": "end"
    }



# --- 1. STATE DEFINITION ---

class AgentState(TypedDict):
    """The state of the research assistant."""
    messages: Annotated[list[BaseMessage], lambda x, y: x + y]
    domain: str
    basic_problem: str
    research_gaps: List[str]
    paper_draft: Dict[str, str]
    next_step: str

# --- 2. AGENT INITIALIZATION (GROQ) ---

# Using Llama 3 70B for high-quality reasoning, or 8B for extreme speed
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.1,
    max_retries=2
)
search_tool = TavilySearchResults(max_results=3)
arxiv_tool = ArxivAPIWrapper()

def create_agent(llm, tools, system_prompt: str):
    """Helper to bind tools and system prompts to the GROQ model."""
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="messages"),
    ])
    if tools:
        return prompt | llm.bind_tools(tools)
    return prompt | llm

# --- 3. NODE DEFINITIONS ---

def explorer_node(state: AgentState):
    """Searches for relevant papers using Tavily and ArXiv."""
    explorer_prompt = f"""You are the SBU Search Specialist using GROQ speed.
    Domain: {state['domain']}
    Current Problem: {state['basic_problem']}

    Task: Find the 3 most relevant current papers.
    Focus on specific methodologies and architectural trends."""

    agent = create_agent(llm, [search_tool], explorer_prompt)
    response = agent.invoke(state)
    return {"messages": [response], "next_step": "reviewer"}

def reviewer_node(state: AgentState):
    """Identifies research gaps in the gathered data."""
    reviewer_prompt = f"""You are the Literature Reviewer.
    Analyze gathered info and identify 3 'Research Gaps'.
    What is missing in {state['domain']} regarding {state['basic_problem']}?"""

    agent = create_agent(llm, None, reviewer_prompt)
    response = agent.invoke(state)

    gaps = [line for line in response.content.split('\n') if 'gap' in line.lower()][:3]

    return {
        "messages": [response],
        "research_gaps": gaps,
        "next_step": "writer"
    }

def writer_node(state: AgentState):
    """Drafts formal paper sections based on the gaps."""
    writer_prompt = f"""You are the Academic Paper Architect.
    Gaps: {state['research_gaps']}
    Draft: Abstract, Intro, Methodology, Proposed Arch, and Conclusion.
    Tone: Formal Academic."""

    agent = create_agent(llm, None, writer_prompt)
    response = agent.invoke(state)

    return {
        "messages": [response],
        "paper_draft": {"full_report": response.content},
        "next_step": "end"
    }

# --- 4. GRAPH CONSTRUCTION ---

def router(state: AgentState):
    return state["next_step"]

workflow = StateGraph(AgentState)

workflow.add_node("explorer", explorer_node)
workflow.add_node("reviewer", reviewer_node)
workflow.add_node("writer", writer_node)

workflow.add_edge(START, "explorer")
workflow.add_conditional_edges("explorer", router, {"reviewer": "reviewer", "end": END})
workflow.add_conditional_edges("reviewer", router, {"writer": "writer", "end": END})
workflow.add_edge("writer", END)

app = workflow.compile()
app



# --- 5. EXECUTION ---
if __name__ == "__main__":
    initial_input = {
        "domain": "Sustainable Energy AI",
        "basic_problem": "Predicting micro-grid stability with high intermittent renewable penetration",
        "messages": [HumanMessage(content="Analyze micro-grid stability research.")],
        "research_gaps": [],
        "paper_draft": {},
        "next_step": ""
    }
    print("⚡ Starting GROQ-powered Research Explorer...")
    for output in app.stream(initial_input):
        for key, value in output.items():
            print(f"\n--- [Node: {key}] ---")
            if 'messages' in value:
                print(value['messages'][-1].content[:] + "...")